### ISSUE TITLE
Feature request: User : Registration Form

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#10]
System only requires Nick, Email, Password, Day of Arrival -> find it difficult to control when it comes to security and safety. Organiser needs to know bio of volunteers 

Adding  an additional field on the registration form (Current city), mark require field for First Name, Last Name and more

**Comment by vuhung** [comment]
Good sense of security!

**Comment by hpdang** [comment]
![screenshot from 2016-05-19 18 08 13](https://cloud.githubusercontent.com/assets/1658742/15400939/bc63b00a-1ded-11e6-91f4-262d74b45de2.png)

(1) Make First Name and Last Name as required field. 
(2) Add below items into the existing registration form: 
- Current city (mark as required)
- Organization, University or Company
- Twitter
- Facebook
- Github

**Comment by DishantK1807** [comment]
Marked First Name and Last Name as required fields

![capture2](https://cloud.githubusercontent.com/assets/7828295/15521369/0d2d2914-2229-11e6-8eb7-66287bf162c1.PNG)

**Comment by hpdang** [comment]
good job!
