### ISSUE TITLE
Feature Request: Languages as profile attributes

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#102]
engelsystem#254

Would be helpful to find shifts where you have a team with your preferred language.User's with same native language can communicate better.

![capture](https://cloud.githubusercontent.com/assets/7828295/16037366/c65dc28a-323d-11e6-886d-e3fc131f06ab.PNG)

Will be adding a new field that will display the native language and other languages that the user knows, that will help other users in choosing the shifts. The process includes:
- [x] Adding new columns in the `Users` table for native langauge and other languages
- [x]  Updating the registration form for native language and marking the field as `REQUIRED`, and other languages
- [x]  Displaying the native language and other languages on the user's page

Will be creating separate issue for each task

**Comment by hongquan** [comment]
How should the database be to store "native language" and "other languages"?
How many "other languages" you want to store?

**Comment by hpdang** [comment]
I don't think this feature is essential.

**Comment by DishantK1807** [comment]
This issue was on engelsystem issue list. Should I stop working on it then?

**Comment by DishantK1807** [comment]
@hpdang : cc : @hongquan  should I work on this issue as this issue was mentioned in Engelsystem issues, or leave it and close the issue?

**Comment by hpdang** [comment]
yes you can work on it.

**Comment by DishantK1807** [comment]
This issue is completed and can be closed.
