### ISSUE TITLE
Cleanup Project: Delete Branches, set up development branch, deploy dev branch to heroku

### ISSUE THREAD

**Issue by mariobehling** [fossasia/engelsystem#135]
We urgently need to improve the project flow. Please:
- [x] Clean up and delete all unused branches
- [x] Set up a branch "development"
- [x] From now on always commit to "development" branch
- [x] Make a biweekly merge on Tuesday and Friday to Master branch - after testing that everything works
- [x] Set up automatic deployment to heroku of development branch

**Comment by sreejakshetty** [comment]
deleted all these branches
captcha-documentation
documentation
shifts_captcha
registration_form
search 
Error_Handling
db_update
events_table
error_shifts
events_table
admin_message
Lang_support
Date/Time-Picker
code_cleanup
color_schema

**Comment by sreejakshetty** [comment]
![screenshot from 2016-06-24 15 55 25](https://cloud.githubusercontent.com/assets/14835922/16335414/1466af4e-3a24-11e6-9ac2-7df31db97139.png)
Deleted all unused branches and set up a new branch "development"

**Comment by mariobehling** [comment]
@kamishettysreeja25 What about the other branches? Why are they still needed. From my perspective only development and master are needed.

**Comment by sreejakshetty** [comment]
@mariobehling there were PR's opened from the branches and commits . deleted those branches now. 
Should I delete the staging branch ?

**Comment by mariobehling** [comment]
yes, please.

**Comment by sreejakshetty** [comment]
Deleted all branches 
date/time_pickerusers @DishantK1807 is working
![screenshot from 2016-06-24 16 23 32](https://cloud.githubusercontent.com/assets/14835922/16336054/05c979cc-3a28-11e6-8c23-2b03529ca03b.png)

**Comment by DishantK1807** [comment]
Deleted the branch `users_table`, will be working on this issue later as we will be implementing database migration. 
Need to make some changes in the date/time_pickerusers branch, will make those changes and make a PR.

**Comment by DishantK1807** [comment]
Deleted branch date/time_pickerusers

**Comment by sreejakshetty** [comment]
deleted shifts_timezone branch 
now only master and development branches present
