### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by hongquan** [fossasia/engelsystem#137]
Some features need change in database schema. Database migration is a way to apply those changes to existing website. This feature is also needed by #136, because we will continuously update a running website on Heroku (staging server)

**Comment by DishantK1807** [comment]
@hongquan : Database migrations as in writing `update.php` files for the changes that we made to the database?

**Comment by DishantK1807** [comment]
And do we need to write migration files for the existing schema or we need to write it for only the changes?

**Comment by mariobehling** [comment]
Just try what is easiest and gets us working and we improve step by step. Rather make a number of smaller improvements than big steps. So, we can speed up the process. No issue should take longer than a day.

**Comment by DishantK1807** [comment]
Currently for database migration, I was going through different libraries for database migration in PHP. As @hongquan  suggested in our previous conversations here, https://groups.google.com/forum/#!topic/engelsystem/Yr4U5yxcfzE we can use https://phinx.org/
I am going through its documentation on how to implement it on our system.

**Comment by DishantK1807** [comment]
@hongquan : I went through the documentation of implementing migrations through https://phinx.org/, 
but it uses classes for implementing migrations, and we do not use any framework in our system so we could implement this library. 
I went through many other libraries as well, like https://packagist.org/packages/php-database-migration/php-database-migration, but it requires framework too. 

What I suggest is that we write migration files on our own. If we make changes in the database we make changes in both, update.sql file and create a updateXX.php file for that. We will take help from the technique which the previous developers used to write the migration files.

The only problem I am facing is that how to run those files in the system.

or there is some other way that you could suggest?

**Comment by hongquan** [comment]
We will run via PHP command line

**Comment by sreejakshetty** [comment]
Used **Phinx** to implement database migrations. 
Implemented database migration for all the changes in **update.sql**  https://github.com/fossasia/engelsystem/commit/212cfb44fa262d9e31c9b6e41ebef93f153c841b
Added documentation to how to migrate the database https://github.com/fossasia/engelsystem/blob/development/db/migrations_documentation.md
![screenshot from 2016-07-11 10 32 17](https://cloud.githubusercontent.com/assets/14835922/16720393/88114b3e-4753-11e6-9afa-207e55650c1e.png)
Tested on local server database is migrated successfully.
This issue can be closed now.

**Comment by mariobehling** [comment]
Good job. Nest issue to follow up on this is here: https://github.com/fossasia/engelsystem/issues/162
