### ISSUE TITLE
Feature Request : Admin : Shift : Batch Deleting shifts

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#14]
https://github.com/engelsystem/engelsystem/issues/247 Batch deleting shifts

**Comment by DishantK1807** [comment]
Tasks:
- [x] Adding checkboxes to all the shifts and a delete button  below or on the side the of Filter button
- [ ] Implementing batch Shift delete, (selecting checkboxes for the shifts to be deleted and deleting those shifts by clicking on delete button)

**Comment by DishantK1807** [comment]
#117

**Comment by DishantK1807** [comment]
PR merged. This issue can be closed.
