### ISSUE TITLE
mysql Error 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#140]
![screenshot from 2016-06-27 17 22 41](https://cloud.githubusercontent.com/assets/14835922/16378826/d408a820-3c8b-11e6-844c-a2c8a21cf323.png)
@DishantK1807 we are getting this error while importing the update.sql file to the database

**Comment by DishantK1807** [comment]
@kamishettysreeja25 : Please check now. Committed the changes to the development branch. Now it runs fine on my system.

**Comment by DishantK1807** [comment]
https://github.com/fossasia/engelsystem/commit/315b7ada5ad25f3111c2a11bfb078b99341ebcdf

**Comment by sreejakshetty** [comment]
Fixed here https://github.com/fossasia/engelsystem/commit/315b7ada5ad25f3111c2a11bfb078b99341ebcdf
