### ISSUE TITLE
reCaptcha is not configurable, keys are in public repo and privacy problems

### ISSUE THREAD

**Issue by msquare** [fossasia/engelsystem#142]
There are a few points about the reCaptcha feature that need to be improved before they can be merged into engelsystem master:
1. Every configuration data (keys) has to be in config.php (and empty values in config.default.php). Never add site-specific private keys to a public repo.
2. Please make this feature able to be turned off via config.php (for example: simple boolean flag "enable recatpcha")
3. Include the google api js file only on pages where it is needed to improve performance, remove dependencies from external providers and to avoid that referrer data from every page is sent to google.

**Comment by msquare** [comment]
This addresses #18, #124, #128, #132

**Comment by DishantK1807** [comment]
@msquare : Will be working on this issue and update the code for the suggestions that you mentioned.

**Comment by DishantK1807** [comment]
#148 , Removed keys from the repository and defined them in config.php

**Comment by DishantK1807** [comment]
#150 
This issue is resolved now and can be closed.
