### ISSUE TITLE
display_msg in user table

### ISSUE THREAD

**Issue by msquare** [fossasia/engelsystem#143]
If you want to customize messages/sentences use the translation files. Texts from database should be translated and so please try to avoid storing interface texts in the database.

My idea:
Please remove the column from database and restore the original text in the source code. Make sure that it uses the translation function `_()` and then implement your wanted message into the `.po` files in the `locale` directory.

**Comment by sreejakshetty** [comment]
> If you want to customize messages/sentences use the translation files. Texts from database should be translated and so please try to avoid storing interface texts in the database.
> 
> My idea:
> Please remove the column from database and restore the original text in the source code. Make sure that it uses the translation function _() and then implement your wanted message into the .po files in the locale directory.

@msquare sure, I will remove the **display_msg** field from user table and restore it to original
 but  it is easy to change the display message directly  in the admin settings page than to change in `.po` files.
Thank you

**Comment by msquare** [comment]
Ok, great. If you want admins to change the message you are right. I talked to @mariobehling sunday and left him an idea about "configure the actual event". The idea is to create an entity containing the event's name, start+end date and start+end date of buildup/teardown. This can also contain a welcome message (not translated). All these infos then can be shown at the register/home page of the engelsystem.
So you can also move the welcome message to a new table and create an admin view allowing him to configure all event related things.

Configuring a welcome message by editing the admin users welcome_msg attribute is a little dirty, if you understand. In fact we delete the admin user with id 1 for every of our events - would this break the feature? Did I understand that right?

Thank you for investigating!

**Comment by sreejakshetty** [comment]
> Ok, great. If you want admins to change the message you are right. I talked to @mariobehling sunday and left him an idea about "configure the actual event". The idea is to create an entity containing the event's name, start+end date and start+end date of buildup/teardown. This can also contain a welcome message (not translated). All these infos then can be shown at the register/home page of the engelsystem.
> So you can also move the welcome message to a new table and create an admin view allowing him to configure all event related things.

Yes, I will make a new  table for `welcome message` . admin can configure them in the admin settings
Do we need to create a new admin view or we can add the features in admin settings ? Presently there is separate view for **admin settings** and **user settings**

> Configuring a welcome message by editing the admin users welcome_msg attribute is a little dirty, if you understand. In fact we delete the admin user with id 1 for every of our events - would this break the feature? Did I understand that right?

Yes , I  also had the same thought while adding the field to User table.

> In fact we delete the admin user with id 1 for every of our events - would this break the feature? Did I understand that right?

I think it would create a problem in the admin settings page also has we have identified admin with **UID = 1** . until the admin UID is 1 there will be no problems.

```
 // Admin settings page   
if( $_SESSION['uid'] == 1){  
  return page_with_title("Admin Settings", array(
      $msg,
      msg(),
```

Thank you :)

**Comment by msquare** [comment]
Ah. I didn't see the admin settings page feature - it seems not to be in the pull request on engelsystem.

I recommend to use the privilege mechanism to check if a user is allowed to access the admin settings.
Insert a new privilege into the privilege table and assign it to the group developers or archangels.
Then check for this privilege in the sourcecode using the `in_array()` function.

**Comment by sreejakshetty** [comment]
I think it is present in the pull request made to engelsystem
![screenshot from 2016-06-28 17 06 45](https://cloud.githubusercontent.com/assets/14835922/16413987/c26d4860-3d52-11e6-91f9-1c90fdd137f0.png)

> I recommend to use the privilege mechanism to check if a user is allowed to access the admin settings.
> Insert a new privilege into the privilege table and assign it to the group developers or archangels.
> Then check for this privilege in the sourcecode using the in_array() function.

sure, I will use this method to check if a user is allowed or not.

**Comment by msquare** [comment]
There may be another misunderstanding: The page you showed is the page for editing the user named "admin" - these are not any "admin settings" applying to the engelsystem itself. Or at least it was not ment to be such a page.

I would really like to introduce an "Settings" page containing engelsystem settings like recaptcha keys, welcome message, event dates, t-shirt-settings and more. This is a feature on my list for a very long time.

**Comment by sreejakshetty** [comment]
Yes , I would like to work on it. I would create a new issue for it.So can you please tell what all should it contain and should it be present under the admin pages.
![screenshot from 2016-06-28 17 14 59](https://cloud.githubusercontent.com/assets/14835922/16414255/3b53f976-3d54-11e6-8c76-b85e322b3971.png)
changing the display message is present on the admin settings page

**Comment by msquare** [comment]
Yes, of course.

**Comment by sreejakshetty** [comment]
created new table Welcome_Message and updated all the files.
https://github.com/fossasia/engelsystem/commit/a1641f834fa644f688f2f08c8d7cb4e7a02a2270
https://github.com/fossasia/engelsystem/commit/53b62ada2581f71ecafd546aabf0aae641310e96
https://github.com/fossasia/engelsystem/commit/3a070ddf139a0bb301b93d7f9aa8c91de46bae04
This issue is completed.

**Comment by sreejakshetty** [comment]
@msquare 
Even after adding an entry in the privileges table.
global `$privilege` gives me same output. So I am unable to add any pages or check access of users. How can I modify `global $privilege`
`Array ( [0] => admin_groups [1] => admin_language [2] => admin_import [3] => register [4] => admin_rooms [5] => admin_angel_types [6] => admin_questions [7] => admin_faq [8] => admin_news [9] => admin_user [10] => admin_import [11] => admin_shifts [12] => admin_active [13] => admin_user_angeltypes [14] => shifttypes [15] => admin_news [16] => user_shifts_admin [17] => admin_user_angeltypes [18] => register [19] => admin_news [20] => admin_user [21] => admin_log [22] => user_shifts_admin [23] => admin_arrive [24] => admin_shifts [25] => admin_free [26] => news [27] => logout [28] => user_settings [29] => user_messages [30] => user_questions [31] => news_comments [32] => user_meetings [33] => user_shifts [34] => user_myshifts [35] => ical [36] => atom [37] => shifts_json_export [38] => angeltypes [39] => user_angeltypes )`
This problem is fixed
thank you

**Comment by msquare** [comment]
Did you assign the new privilege to a group? This can be done via admin menu "group rights".

**Comment by sreejakshetty** [comment]
@msquare I have assigned it. Fixed the issue. 
Thank you
