### ISSUE TITLE
Improve user export

### ISSUE THREAD

**Issue by msquare** [fossasia/engelsystem#144]
There are a few things with the user export function that can be improved.

My ideas are:
1. The export is located under "FRAB import and export". FRAB is a system to manage events and has nothing to do with users. Restore this to "Frab import" and locate the export button on top of the users list (`users_list_controller()` and `Users_view()`).
2. The export writes a file to the file system. This can lead to problems because not all environments allow this and because userdata including hashes is written to the filesystems tmp dir - and every server user can read this.
3. Exclude password hashes from export!
4. Make sure to put CSV content into a .csv file (not .xls) - I think this is already fixed.
5. Move the code to a `users_export` function in the `users_controller.php` for this feature

**Comment by DishantK1807** [comment]
Current status:
- Restored the Frab Import page to original status.
- Created a new page for Import and export of user data.

Next 
- Remove password hashes from the exported database

**Comment by DishantK1807** [comment]
Update status: 
- Removed password hashes from the user export.

This issue is resolved and can be closed.
