### ISSUE TITLE
Feature Request: Admin: Settings Page

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#145]
**Explanation:**
Creating a new settings page for admin containing all the engelsystem settings like recaptcha keys, welcome message, event dates, t-shirt-settings and more.

**Comment by msquare** [comment]
This can include the following steps and contents:
1. create a privilege for accessing the settings page
2. create a settings table (event_name, buildup_start_date, event_start_date, event_end_date, teardown_end_date, event_welcome_msg)
3. create a model containing functions to insert+update settings
4. create controller + view containing edit form to edit the settings

If you want to move settings from config.php to the settings table you can also include:
1. T-Shirt feature enabled (replace every occurence `$enable_tshirt_size` with new value from settings table)
2. reCaptcha enabled
3. reCaptcha key+url

**Comment by mariobehling** [comment]
@kamishettysreeja25  Please provide a mockup/screenshot where you see that page added.

**Comment by sreejakshetty** [comment]
@mariobehling @msquare 
This is the screenshot of the new `Settings page`
![screenshot from 2016-07-02 10 07 30](https://cloud.githubusercontent.com/assets/14835922/16538264/fee81b84-403c-11e6-8cf3-1763dd4a8547.png)
The page is added under the `admin menu`.

**Comment by sreejakshetty** [comment]
https://github.com/fossasia/engelsystem/commit/ae31ce98ed24868715a74634d85ce4b5793c5faf
https://github.com/fossasia/engelsystem/commit/c7d9203691c88bfd8f91064b5cd714630d4be118
https://github.com/fossasia/engelsystem/commit/5e03a7f2748ee63a2320255422fe8664d0cf5a1b
This issue is fixed.

**Comment by sreejakshetty** [comment]
https://github.com/fossasia/engelsystem/commit/a80d75cc6f9a69f3ea7913c1bdc7f912b222ce8d
fixed indentation and codacy issues.
