### ISSUE TITLE
Feature Request : Admin : Shift : Editing existing shift

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#15]
We can have a option to Copy existing shift and make a new shift from it simply by changing the date and time.

**Comment by sreejakshetty** [comment]
@hpdang can you explain it briefly  as presently in create shifts under admin . we can choose a particular shift and edit date and time . Is any other feature required ?
![screenshot from 2016-05-30 20 39 48](https://cloud.githubusercontent.com/assets/14835922/15652885/f9c859de-26a6-11e6-94c3-c1cd719affe1.png)

**Comment by hpdang** [comment]
when you edit an existing shift, it will become a new shift. The old one will no longer exist. I would like to have a Copy/Duplicate function where we can produce a new shift from an existing shift and the existing shift is still the same.

**Comment by sreejakshetty** [comment]
Once admin presses the edit button , admin is redirected to edit shifts page where admin can either update the existing shift or create a new shift by simply changing date or time from the existing shift ,
![screenshot from 2016-06-17 14 49 49](https://cloud.githubusercontent.com/assets/14835922/16146259/c6b9384a-349a-11e6-8a6e-af36131a587f.png)
