### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#156]
- [x] create docs folder in the root directory and move all the documentation.
- [x] Create a Readme for HEROKU
- [x] Create a Readme for INSTALLATION_DOCKER

**Comment by hpdang** [comment]
Ok, I have seen you already work on it. I have re-organized the readme file and linked the installation instructions from the main file. I also took out the Features info. That can go into the main Readme.md.

@kamishettysreeja25 I have copied the installation info from the main page temporarily into the beginning of https://github.com/fossasia/engelsystem/blob/development/docs/INSTALLATION_SERVER.md. Please merge the installation info within that file.

Next steps:
- [x] Create a Readme for HEROKU
- [x] Create a Readme for INSTALLATION_DOCKER

**Comment by sreejakshetty** [comment]
@hpdang Sure. Thank you. 
I will work on docker installation and create Readme for Heroku.

**Comment by sreejakshetty** [comment]
Added Heroku documentation
https://github.com/fossasia/engelsystem/blob/development/docs/HEROKU.md

**Comment by sreejakshetty** [comment]
Added docker installation and added dockerfile
https://github.com/fossasia/engelsystem/blob/development/docs/INSTALLATION_DOCKER.md
https://github.com/fossasia/engelsystem/blob/development/Dockerfile
