### ISSUE TITLE
Improving code quality: Fix circle ci and codacy issues

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#158]
Circle ci Issue is due to different php versions in lock file.
![screenshot from 2016-07-11 20 23 52](https://cloud.githubusercontent.com/assets/14835922/16735096/73b33786-47a5-11e6-89f8-95c430e52426.png)
codacy issues:
**guest_login.php** 
Issue found:
white space found at end of line at different line
**admin_import**  
Issues found:
 export_xls accesses the super-global variable $_SERVER.
The function export_xls() contains an exit expression.
Avoid variables with short names like $fp. Configured minimum length is 3.

**Comment by DishantK1807** [comment]
@sreeja: the fuction `export_xls()` no more exists in the updated code

**Comment by sreejakshetty** [comment]
@DishantK1807 okay. We need to fix the circle ci error first. The build will fail till we fix circle-ci

**Comment by DishantK1807** [comment]
@sreeja: the php version in `circle.yml` is 5.4.5, We should set the php version in `composer.lock` `>=5.4.5` for all the require parameters

**Comment by DishantK1807** [comment]
for the errors reported by codacy and circle-ci, I'll remove whitespaces from all the files, and you check which PHP version is most suitable for the require parameters, for the database migrations.

**Comment by sreejakshetty** [comment]
so we need to update composer.lock right or change circle.yml ?

**Comment by DishantK1807** [comment]
`composer.lock`,  there are different values of PHP version in `composer.lock` file some are below 5.4

**Comment by DishantK1807** [comment]
@sreeja: 

> Phinx requires at least PHP 5.3.2 (or later).

from the Phinx documents

**Comment by sreejakshetty** [comment]
@DishantK1807 We can remove the composer.lock files and vendor files. Those files are installed when we run composer update. Now the circle-ci has passed when I changed the php version in composer.lock

**Comment by sreejakshetty** [comment]
Fixed circle-ci issue. All the tests are fixed.

**Comment by DishantK1807** [comment]
@sreeja: I guess that `composer.lock` file is required when deploying on heroku.

**Comment by sreejakshetty** [comment]
@DishantK1807 Yes, but it is not necessary in the github repo. while we are deploying on heroku we need to run `composer update` . This will automatically generate the composer.lock file. 
I will remove composer.lock and other vendor files to reduce the size of the repo

**Comment by DishantK1807** [comment]
@sreeja: We can close this, if this issue is complete.
