### ISSUE TITLE
Improving Code quality: Removing whitespaces, translating comments and soving CI issues

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#159]
- [x] Removing white spaces from all the files
- ~~Translating comments from German to English~~ This doesnt have priority right now. (Mario)
- [x] Solving errors report by Circle-CI and Codacy
- [x] Fixing code climate issues

**Comment by DishantK1807** [comment]
Whitespaces removed and translated comments in all the files in `pages` folder, 
Coday error reduced from 854 to 786

**Comment by sreejakshetty** [comment]
Please we will make lesser number of commits and not pollute github. msquare will find it difficult to review all the commits.

**Comment by sreejakshetty** [comment]
Fixed circle-ci issue. Now only codacy errors have to be fixed.

**Comment by DishantK1807** [comment]
Whitespaces removed from the controller files,
Codacy errors removed from 786 to 754

**Comment by sreejakshetty** [comment]
@DishantK1807 
There are 754 issues. 
Info: 392
Warnings: 362
We both can divide the issues and fix the issue fast.
Thank you

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Yes, we can divide them.
Currently I'm working on removing whitespaces from all the files. I am done with controller, helper and Pages. You can work on other issues on the files in the mentioned folder so that there is no conflicts.

**Comment by DishantK1807** [comment]
Whitespaces removed from the helper files,
Codacy errors removed from 754 to 747

**Comment by sreejakshetty** [comment]
@DishantK1807 Sure.

**Comment by sreejakshetty** [comment]
I am working on all the view files.

**Comment by DishantK1807** [comment]
Whitespaces removed from the Model files,
Codacy errors removed from 747 to 688

**Comment by DishantK1807** [comment]
Whitespaces removed and translated comments in the System files,
Codacy errors removed from 688 to 589

**Comment by sreejakshetty** [comment]
Resolved codacy issues
Codacy errors removed from 594 to 578

**Comment by sreejakshetty** [comment]
https://codeclimate.com/github/fossasia/engelsystem/pull/160
Code climate issues
Currently there are 924 issues reported.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: That's only for the current PR #160. We have a total of 4,294 issues. 
I've added a code climate issue badge to the `readme.md` file.

**Comment by DishantK1807** [comment]
Resolved codacy issues
Codacy errors reduced from 578 to 492
https://www.codacy.com/app/dishant-khanna1807/engelsystem_2/dashboard?bid=3396823

**Comment by DishantK1807** [comment]
Resolved codacy issues
Codacy errors reduced from 578 to 428
https://www.codacy.com/app/dishant-khanna1807/engelsystem_2/dashboard?bid=3396823

**Comment by DishantK1807** [comment]
Codacy issues resolved.
Will start looking into code climate issues

**Comment by DishantK1807** [comment]
Reviewed all the code climate issue. Code climate issues are generally due to:
- Request to super global variable
- Camel case
- Whitespaces(fixed)
- length of variable name(fixed)
- Using unused variables (fixed)

This issue can be closed.

**Comment by vuhung** [comment]
How about reviewing code by looking at the "code smells"?

**Comment by mariobehling** [comment]
Thanks.
