### ISSUE TITLE
Feature Request : Admin : Shift : Date/Time picker for creating shifts 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#16]
At the moment admin needs to type in date and time by hands as we can see below
![screenshot from 2016-05-19 09 33 40](https://cloud.githubusercontent.com/assets/14835922/15382174/f01c5936-1da4-11e6-8bec-1658e2938d29.png)

**Comment by sreejakshetty** [comment]
![screenshot from 2016-05-28 20 28 05](https://cloud.githubusercontent.com/assets/14835922/15627996/bab960a2-2512-11e6-9723-e1e9ae5ff6bc.png)
![screenshot from 2016-05-28 20 27 49](https://cloud.githubusercontent.com/assets/14835922/15627997/babbeb38-2512-11e6-8e82-41a2f500a9b6.png)

**Comment by vuhung** [comment]
Let's find similar part of the code that can use date picker.

**Comment by sreejakshetty** [comment]
![screenshot from 2016-05-30 20 52 25](https://cloud.githubusercontent.com/assets/14835922/15653174/d7f2a0d8-26a8-11e6-857c-0fec58b7b307.png)
![screenshot from 2016-05-30 20 52 05](https://cloud.githubusercontent.com/assets/14835922/15653175/d8551920-26a8-11e6-947c-586e60e09c25.png)

**Comment by hpdang** [comment]
I didn't see the changes on the test server. 

http://107.170.29.227/engelsystem/public/
username : admin
password : gsoc_foss

**Comment by sreejakshetty** [comment]
@hpdang 
Please check on this 
http://107.170.88.225/engelsystem/public
username : admin
password : gsoc_foss

**Comment by hpdang** [comment]
thanks, so we will this one from now on? Yes it works but calendar is in German.

**Comment by sreejakshetty** [comment]
Yeah , we will be using this one for testing it online from now.
The calender used in register page is also in german .I would like to create a issue for this and fix it .
