### ISSUE TITLE
Implement an installation flow similar to wordpress

### ISSUE THREAD

**Issue by hpdang** [fossasia/engelsystem#161]
The installation could be simplified and Wordpress shows how it can be done. Please implement an installation flow like at https://codex.wordpress.org/Installing_WordPress#Famous_5-Minute_Install including the following:
- [x] Change engelsystem/config/config.default.php to engelsystem/config/config-sample.default.php
- [x] Keep the config-sample database info empty
- [x] Installation script where admin can define name and email at the beginning
- [x] Document the new flow in a blog post and in all installation readme's

**Comment by sreejakshetty** [comment]
#211 
Implemented Installation script where admin can define name, email and password at the beginning

**Comment by sreejakshetty** [comment]
Fixed here #211
