### ISSUE TITLE
Installing the system on an online web server

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#17]
When I install the system online on a web server, the dropdown arrow on the upper right corner is not working, tried installing the system many times but the problem still remains. Is it the issue with the server or something else?

**Comment by hongquan** [comment]
What do you mean by "not working"? What is your expectation and what it actually behaves?

**Comment by DishantK1807** [comment]
![screenshot 9](https://cloud.githubusercontent.com/assets/7828295/15385851/eb1e41ac-1dc1-11e6-8261-829de70359a5.png)

@hongquan : clicking on the drop-down arrow on the upper right corner results in a drop-down menu, in which there are options like, settings, logout, shifts, locales.
but when I click on it nothing happens
Like it's happening in the images below
![sc2](https://cloud.githubusercontent.com/assets/7828295/15385913/5f4a7096-1dc2-11e6-8674-483c98b63660.PNG)

**Comment by hongquan** [comment]
Does the URL in address bar change after you click to a menu item? It does in my side. If it does, it means the menu works.

**Comment by DishantK1807** [comment]
the url does change. 
a "#" symbol is added at the end of URL

**Comment by hongquan** [comment]
Where do you get the code from? In my side, the URL change to `?set_locale=de_DE.UTF-8` when I click to Deustch
