### ISSUE TITLE
Correct hardcoded links/references in localization

### ISSUE THREAD

**Issue by mariobehling** [fossasia/engelsystem#183]
The references are hardcoded in the [localization](https://github.com/fossasia/engelsystem/tree/master/locale) and they should not be.

e.g. /var/www/html/engelsystem/includes/sys_menu.php:63 (https://github.com/fossasia/engelsystem/blob/master/locale/en_GB.UTF-8/LC_MESSAGES/default.po) or in the German po /Users/msquare/workspace/projects/engelsystem/includes/sys_menu.php:49
msgid

Please ensure that it works on all systems and setups.

**Comment by DishantK1807** [comment]
Will fix this.

**Comment by mariobehling** [comment]
Actually these links are just comments. They are coming from translating applications. So, disregard and continue with something else, please. Closing it.
