### ISSUE TITLE
Implementing MVC for the existing controller files

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#190]
There are some already created controller files that contains sql queries in them.
- [x] user_controller.php
- [x] shifts_controller.php
- [x] admin_user_controller.php

**Comment by DishantK1807** [comment]
#163

**Comment by DishantK1807** [comment]
Fixed here: #202

**Comment by sreejakshetty** [comment]
@DishantK1807 There are no sql queries in `admin_user_controller.php`. Why it is included in this issue?

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Now there are not, but earlier there were. When I created the issue. Check your previous PR. You might have forgotten to include it.

**Comment by DishantK1807** [comment]
PR merged. Closing this issue.
