### ISSUE TITLE
Writing tests for Model files

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#193]
Parent issue: #191 

Will be writing tests for each model files. Dividing this issue into smaller ones.

**Comment by sreejakshetty** [comment]
@DishantK1807 Can we postpone this issue. I would like to work on re-factoring model files. There are many functions created with same functionality. After Re-factoring you and I can divide the work and complete.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: The test codes will mostly check create, delete and return(count). Other functions might be multiple and you can work on refactoring, I am currently working on the already existing model files. Else if the refactoring is large, create issues for multiple files and we can work on refactoring fast.

**Comment by sreejakshetty** [comment]
@DishantK1807 Its better to refactor the model files decrease unused and duplicate functions first and then write tests. Already existing files also need a re-factoring we have created duplicate functions. we need to resolve it first. We can delete already existing model files and move the functions into other model files.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Okay. I'll postpone it. Create issues for refactoring and we can work on it fast.
