### ISSUE TITLE
Developing Shifts Page

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#2]
Currently shifts page need to be developed and we can add the following features to it.
#254 having shifts with a preferred language team , set native language.
#247 batch deleting shifts option.
#246 editing an existing shift.
#245 date picker for creating shifts

**Comment by sreejakshetty** [comment]
This issue can be divided into multiple small issues .

**Comment by vuhung** [comment]
yeah, divide and conquer

**Comment by sreejakshetty** [comment]
This is issue can be closed has this is solved in multiple issues.
