### ISSUE TITLE
Feature Request: Admin: Import User Data from Spreadsheet

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#20]
function to import data from a spreadsheet to the system

**Comment by sreejakshetty** [comment]
xcal and xml files are allowed for importing to create shifts , delete rooms,update shifts etc.Do we require any more options?
![screenshot from 2016-06-04 07 42 28](https://cloud.githubusercontent.com/assets/14835922/15797019/f2068bec-2a27-11e6-9d64-c83486d3cf7f.png)

**Comment by vuhung** [comment]
I don't understand the system much but for your question,  I think:
1. Let's go with it
2. Try and see they are good or bad and adapt if needed.

The perspectives of developer testing is, as a developer, you are also the
very first user.

May Quan, Mario will give you some advice.

No excuse for being brief on mobile.

**Comment by mariobehling** [comment]
@kamishettysreeja25 Could you please tell me the origin of that feature request. Who made that request?

**Comment by sreejakshetty** [comment]
![imageedit_2_5252465184](https://cloud.githubusercontent.com/assets/14835922/16511735/0c5b7ed6-3f71-11e6-81f8-b656c96fc683.png)
Presently, I have implemented the import function for user data in All Angels page. 
Is this view fine or should I make a new admin page for this?

**Comment by sreejakshetty** [comment]
@mariobehling @hpdang 
![screenshot from 2016-07-01 12 15 40](https://cloud.githubusercontent.com/assets/14835922/16513850/903c8a10-3f85-11e6-808f-dd214a099491.png)
Presently there are 38 rows in the User table. Will the imported file contain the same number of fields or only the required fields. For validation should I validate all the fields?

**Comment by DishantK1807** [comment]
@kamishettysreeja25: #19, these are same issues. Are you working on this now?

**Comment by sreejakshetty** [comment]
#19 same issue. This issue can be closed.

**Comment by sreejakshetty** [comment]
**Import user data view**. Admin needs to upload the file
![screenshot from 2016-07-07 11 42 09](https://cloud.githubusercontent.com/assets/14835922/16644143/477cc8a0-4438-11e6-8edb-6d6a30091512.png)
When there is no error in the database. **success message** is shown.
![screenshot from 2016-07-07 11 44 55](https://cloud.githubusercontent.com/assets/14835922/16644141/4286e56a-4438-11e6-8032-2f871992052b.png)
When there is an error in the database. **error message** is shown.
![screenshot from 2016-07-07 11 44 22](https://cloud.githubusercontent.com/assets/14835922/16644142/471f4b30-4438-11e6-8aa7-7eafde12da9e.png)
When no file is selected. **Error message** is shown
![screenshot from 2016-07-07 11 47 55](https://cloud.githubusercontent.com/assets/14835922/16644207/b578a5f4-4438-11e6-83dc-192d9341cff1.png)
