### ISSUE TITLE
Features: Installation script 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#212]
parent issue: #161 
These are features need to implemented.
- [x] database migrations directly through script
- [x]  Document how to change url from example.com/engelsystem/public to example.com/engelsystem/ issue #213 
- [x]  install.php should be redirected only once for one database.

**Comment by sreejakshetty** [comment]
@hongquan 
Can I create a index.php file in the root folder of engelsystem which redirects to engelsystem/public/index.php file to resolve the directory listing problem.

**Comment by hongquan** [comment]
Replied via #211

**Comment by sreejakshetty** [comment]
Fixed here #211
