### ISSUE TITLE
Importing tables through script 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#216]
Implementing importing tables through script while installing engelsystem.
Points to be taken care while importing tables https://github.com/fossasia/engelsystem/pull/211#issuecomment-238011853
- strategy to give browser fast response. 
- split the queries to many batches, run one by one, or implement asynchronous task (rather advance).

**Tasks**
- [ ]  implement a script to import the tables in install.sql and update.sql
- [ ] Document new flow in a blog post and update the docs

**Comment by hongquan** [comment]
Note that, this one should not be called "migration". You will cause confusing with other "migration" feature you did before. "Migration" means you already have database with tables and you are changing thoses tables.
Here, in your install case, you have no table at first.

**Comment by sreejakshetty** [comment]
@hongquan 
Updated the title and the description.
Thank you

**Comment by sreejakshetty** [comment]
Fixed here #211
