### ISSUE TITLE
Feature request: User : Shifts : Date/Time picker while choosing shifts 

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#23]
Time picker for selecting shifts

At the moment user can select the date from a drop-down menu, however, user have to insert the time manually

**Comment by mariobehling** [comment]
Please provide a screenshot here before making a pull request. Please add all issues to milestones.

**Comment by DishantK1807** [comment]
@imujjwal96: make a PR to branch `date/time_pickerusers`

**Comment by imujjwal96** [comment]
@DishantK1807 OK!

**Comment by DishantK1807** [comment]
Made commits to the development branch.
- https://github.com/fossasia/engelsystem/commit/4e1ed33e27c80bd84537b499cc981cc03ba63ef7
- https://github.com/fossasia/engelsystem/commit/a89d18eba8d636f4b3c3a7412fde9e2a9bb84330

**Comment by DishantK1807** [comment]
![date_picker1](https://cloud.githubusercontent.com/assets/7828295/16356696/af1d0638-3aff-11e6-9477-643840019e1f.png)

This issue can be closed
