### ISSUE TITLE
Remove Welcome message from Settings

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#231]
Display message in Settings
![display message exist 1](https://cloud.githubusercontent.com/assets/7828295/17955389/727548d8-6a9f-11e6-814f-7842b93340b8.png)

Display message in Admin Settings
![welcome message in admin settings](https://cloud.githubusercontent.com/assets/7828295/17955391/74089de4-6a9f-11e6-8877-4ed79aad143b.png)

@kamishettysreeja25: There is display welcome message in both, Admin Settings and Settings. 
Are those same things? If yes, we should remove it from Settings and keep it in Admin Settings.

**Comment by sreejakshetty** [comment]
@DishantK1807 
Welcome message is for registration page. As msquare told me to create a new table for it I have created it. 
Whereas event welcome message is for displaying event message in the login page where we show all the fields event name, event start date, all the fields in settings page.
Once we have designed the login page layout we can show all admin settings page fields there.
They will be used for different purposes.
You can close this issue now.
Thank you
