### ISSUE TITLE
Create an event?

### ISSUE THREAD

**Issue by userdimi** [fossasia/engelsystem#233]
Hey guys,

where can I create an event?

**Comment by sreejakshetty** [comment]
Hi @userdimi 
Only admin can create events. Under Admin press the dropdown you have **create events** where we can create new events. Below image shows the create events page.
![event1](https://cloud.githubusercontent.com/assets/7828295/17839161/cb05af28-67fd-11e6-892c-fc0b854cf4e2.png)

**Comment by userdimi** [comment]
Hi @kamishettysreeja25 

thank you for your answer.

I created a user during the installation of the application. I'm not sure if the user has admin rights. Where can I see my rights and permissions? If I press the Admin Button down I don't find "create event" at the list. 
<img width="1268" alt="screen shot 2016-10-10 at 23 03 26" src="https://cloud.githubusercontent.com/assets/2900264/19251118/ff0aacf8-8f3d-11e6-89f9-d03c8a23f220.png">

**Comment by sreejakshetty** [comment]
@userdimi 
Please check whether all the tables are imported to the database successfully.
![screenshot from 2016-10-12 17 45 09](https://cloud.githubusercontent.com/assets/14835922/19309615/bd0e4c12-90a3-11e6-96aa-fc19ef7c2f3d.png)
Thank you :)

**Comment by userdimi** [comment]
Hey @kamishettysreeja25. Thank you for your answer. After a look at db I found the user admin. I logged me as admin and found the Option to creat Event. Thank you for the hint!!!
