### ISSUE TITLE
Implementing Search

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#3]
implementing search to select users

**Comment by hpdang** [comment]
please explain. What do you want to search for? Where do you want to implement Search, please provide a screenshot?

**Comment by sreejakshetty** [comment]
![screenshot from 2016-06-21 12 06 46](https://cloud.githubusercontent.com/assets/14835922/16220187/cf3ebdf8-37a8-11e6-85f8-9d8406980561.png)
@hpdang We can add search option in All Angles Page so that admin can easily search for users as in active angels page and arrived angels like this
![screenshot from 2016-06-21 12 10 10](https://cloud.githubusercontent.com/assets/14835922/16220222/1bb3915e-37a9-11e6-84c6-afc58cf021b2.png)
