### ISSUE TITLE
Add more items to registration form

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#35]
#10

Add below items into the existing registration form:
- Current city (mark as required)
- Organization, University or Company
- Twitter
- Facebook
- Github

![bc63b00a-1ded-11e6-91f4-262d74b45de2](https://cloud.githubusercontent.com/assets/7828295/15564739/c7d23638-2332-11e6-8ddb-7143b49a89dd.png)

**Comment by DishantK1807** [comment]
![screenshot 14](https://cloud.githubusercontent.com/assets/7828295/15626444/afbcb080-24e2-11e6-9a2c-36cca892556d.png)

Any other fields that could be added except the mentioned ones?

**Comment by DishantK1807** [comment]
![screenshot 14](https://cloud.githubusercontent.com/assets/7828295/15628835/5d682322-2529-11e6-85dc-8f2c6decc0a1.png)

Added new fields to the registration form and test on the online server

**Comment by hpdang** [comment]
good job!
