### ISSUE TITLE
New Themes 

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#4]
Designing new themes/color schemes for Engelsytem.

**Comment by mariobehling** [comment]
Before implementing a new feature/functionality/design, please always post a mockup/screenshot in the issue. So others have a chance to give feedback.

**Comment by DishantK1807** [comment]
![screenshot 19](https://cloud.githubusercontent.com/assets/7828295/15804486/a5a4e96e-2b27-11e6-922f-45becc97a305.png)
![capture1](https://cloud.githubusercontent.com/assets/7828295/15804488/a83752b6-2b27-11e6-99b1-d50aeba11fba.PNG)

This issue can be closed as of now as 2 color schemes have been implemented for now. I've other developers who are interested in adding more themes. I'll be creating separate issues for them to work on once they get on board with the project.
