### ISSUE TITLE
Error update for guest_login.php

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#49]
@quan: as reported by you, will solve these errors.
[Fri Jun  3 18:42:21 2016] PHP Notice:  Undefined index: oragnization in /home/quan/Works/FOSSASIA/engelsystem/includes/sys_page.php on line 15

> [Fri Jun  3 18:42:21 2016] PHP Notice:  Undefined variable: organisation in /home/quan/Works/FOSSASIA/engelsystem/includes/pages/guest_login.php on line 194

**Comment by DishantK1807** [comment]
error solved. This issue can be closed.

**Comment by vuhung** [comment]
@dishant: you should write more comprehensive issue titile.
