### ISSUE TITLE
Adding more languages required for localisation

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#5]
Implement localization in different languages as it will make this system reach many people across the world.

currently implementing:
 1) Punjabi(Indian)
 2) Bulgarian 
 3) French
 4) Spanish
 5)Malayalam (Indian)
 6)Nepali (Indian)
 7)Tamil(Indian)
 8)Urdu (India)
 9)English-UK
 10) Marathi (India)
 11) Kannada (India)
 12) Gujarti (India)
 13)Filipino (Philippines) 
 14) Bengali (India)
 15) Chinese (Simplifies, China)
 16)Hungarian (Hungary)
 17)Indonesian (Indonesia)
 18)Portuguese (Portugal)
 19) Swedish ( Sweden)

**Comment by mariobehling** [comment]
Please add a screenshot/mockup here how the changes will look like.

**Comment by DishantK1807** [comment]
Implementing localization will result in different changes for different languages

an example , when we implement localization for French language the changes would like : 
![capture](https://cloud.githubusercontent.com/assets/7828295/15385360/b8d64bd4-1dbe-11e6-9c1a-8456cb30d9aa.PNG)

**Comment by arunimasharma** [comment]
Hey @DishantK1807  This is in continuation to our prior conversation, as discussed I would like to contribute for this issue. Please let me know how would you like me to kick-start!
Cheers!

**Comment by DishantK1807** [comment]
@arunimasharma : Hello, it's good to have you on board with the project. Kindly go through the code for now. I'll be creating a new issue for you to work on for specific languages so that other developers do not work on same languages.

Cheers!

**Comment by arunimasharma** [comment]
@DishantK1807 : Roger that! I'll study the code and kickstart shortly! 

Cheers!

**Comment by vuhung** [comment]
Nice to have @arunimasharma on board!

**Comment by DishantK1807** [comment]
This issue can be closed as I've uploaded the languages to be updated by me and the PR is merged. Beginner developers will work on other issues #52.

**Comment by arunimasharma** [comment]
@vuhung : Thank you :)
