### ISSUE TITLE
Language support-1

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#52]
#5

Implement localization in different languages as it will make this system reach many people across the world.

**Comment by DishantK1807** [comment]
@arunimasharma: Please comment the languages that you would like on from Issue #5 and provide us with a mockup/ screenshot. You can add other languages too if they are not mentioned earlier in the issue. Let's code!

Cheers!

**Comment by arunimasharma** [comment]
@DishantK1807 : Here is the list of languages that I can work on, please feel free to suggest more/ advise for replacement in case you find befitting. The list of languages:
1. Bengali
2. Marathi
3. Nepali
4. Bulgarian
Suggestion:
5. Vietnamese

I will be adding mockup/ screenshot herein in a while. Looking forward to work with you, Happy Coding!

Cheers!

**Comment by DishantK1807** [comment]
@arunimasharma : have the set up the system on your device already? If no, please do that first.

Cheers!

**Comment by arunimasharma** [comment]
@DishantK1807 : Yes, as mentioned by you in the initial conversations. I will set-up now, soon. Going through the code for now.

Cheers!

**Comment by vuhung** [comment]
I can contribute to Vietnamese translation.

Good idea (y)

No excuse for being brief on mobile.

**Comment by arunimasharma** [comment]
@vuhung : Thank you. It will be a pleasure. I will write .po files and ask for help in some difficult Vietnamese translation and validation. 

Cheers!

**Comment by DishantK1807** [comment]
Languages implement as of now:
- Bulgarian
- English UK
- French
- Irish
- Hindi-IN
- Hungarian
- Punjabi-IN
- Spanish
- Chinese- simplified
- Tamil-IN

@arunimasharma : Please add more languages. 
Cheers!

**Comment by arunimasharma** [comment]
@DishantK1807 : Alright!

**Comment by DishantK1807** [comment]
@arunimasharma : Please update the list of languages that you are working on, so we don't have other developers working on the same languages. Nice to have you on board. :) 

Cheers!

**Comment by arunimasharma** [comment]
@DishantK1807 : Thank you :) Here's the list of languages I will be working on, however, if time permits, I will contribute for more.

1) Finnish (Finland)
2) Nepali (Indian) 
3) Urdu (India)
4) Marathi (India)
5) Kannada (India)
6) Gujarati (India)
7) Indonesian (Indonesia)
8) Portuguese (Portugal)
9) Swedish ( Sweden)
10) Vietnamese (Vietnam)
11) Mexican (Mexico)
12) Latin (South America)
13) Romanian (Romania)
14) Persian (UAE)
15) Malayalam (Indian)
16) Japanese (Japan)
17) Norwegian Bokmal (Norway)
18) Greek (Greece)
19) Korean (North Korea)
20) Latvian (Latvia)

Cheers!

**Comment by mariobehling** [comment]
Thanks a lot. This is sufficient for the moment. We need system features now.
