### ISSUE TITLE
UI/UX Design : Login Page 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#53]
We could add the jobs/team description in the menu bar and make the login simple and neat  by having just the username and password as shown below.
![screenshot from 2016-06-05 11 01 10](https://cloud.githubusercontent.com/assets/14835922/15803789/d3d78302-2b0c-11e6-9b4a-a970af38ea79.png)

**Comment by hpdang** [comment]
I think we can stay with the original login page for now. It is already very clear and tidy, you can click on Job Description under What Can I do. The Registration button is also big and clear. Let's keep it that way. 

![screenshot from 2016-06-06 10 08 10](https://cloud.githubusercontent.com/assets/1658742/15815630/a1384572-2bce-11e6-8941-42ad37c5455c.png)
