### ISSUE TITLE
UI/UX Design : Register Page

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#54]
1-Changing the layout ,  currently the layout  is unordered and I plan to make it more ordered and user-friendly. As we can see the layout looks a bit confusing 
![screenshot from 2016-06-05 11 05 18](https://cloud.githubusercontent.com/assets/14835922/15803802/695ca812-2b0d-11e6-9f0e-6fc1b94b0ff9.png)
I will be dividing the layout into 2 pages. One for personal details and other for volunteer preferences as shown below.In the volunteer preferences the user can set priority also.
![screenshot from 2016-06-05 11 03 43](https://cloud.githubusercontent.com/assets/14835922/15803797/3ab912ac-2b0d-11e6-97ad-ed744777d8b6.png)
![screenshot from 2016-06-05 11 04 00](https://cloud.githubusercontent.com/assets/14835922/15803798/3aba1012-2b0d-11e6-954a-0eb64c4b47bf.png)

**Comment by hpdang** [comment]
Yes, let's think how to make this registration page a bit more organized. I can see that in your proposed design, users need to go to the next tab/page to select Preferences in other to complete the form while the original everything happens in one single page. (I think fewer clicks is more efficient). I suggest you look at other log-in pages of different services and select the one you think best then add it here.

**Comment by sreejakshetty** [comment]
Instead of a two page process for registration.We can add the volunteer preferences below the personal details and the user can do the same registration with just one click at the bottom of the page.
Many sites have the same 
![screenshot from 2016-06-06 14 26 16](https://cloud.githubusercontent.com/assets/14835922/15817430/93977420-2bf5-11e6-9c27-a87e0f34d3b8.png)

**Comment by vuhung** [comment]
+1 with this simple registration process.
