### ISSUE TITLE
Improving Documentation: code readability 

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#56]
Currently there is no documentation and it is difficult for the  new contributors to contribute. The comments in the code are in german, which makes it a difficult to understand . I would also like to improve the documentation of Engelsystem so that more people can contribute to it in the future.

**Comment by DishantK1807** [comment]
@sreeja: regarding this issue I have a suggestion. We can work on it together. Let's not create a separate branch for it as of now, we work on the codes and add comments side by side in the code which we are working on and push the code. This will save a lot of time and effort as it would be easy to add comments while working on the code. and later for during the milestone 14 week, you or we can work together for adding comments to rest of the files on a separate branch for documentation. What's say?

**Comment by sreejakshetty** [comment]
@DishantK1807 sure,we will be following this whenever we are coding . we will add comments while working on the code and change the comments from german to english where ever it is possible.Later during the milestone 14 week , we can work together for adding comments to rest of files.
Cheers :)
