### ISSUE TITLE
Code and branch cleanup

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#57]
Removing unused legacy codes that do not affect the system now and stale branches that are not required, from the system to keep it clean.

**Comment by DishantK1807** [comment]
Branches: stats, remove-sessionhelper, edit-news-comments are stale and can be deleted. Theme branch not required as we will be working on color_scheme branch, so can be deleted.

**Comment by DishantK1807** [comment]
update.d directory and update.php are legacy codes and can be removed as they do not affect the system.

**Comment by DishantK1807** [comment]
For removing files and directories, do I need to create a separate branch or can delete directly from the master?

**Comment by sreejakshetty** [comment]
https://github.com/engelsystem/engelsystem/pull/252
As asked here, we can delete  update.d directory and update.php files has told by @msquare .
@DishantK1807 I will also be helping you in this issue . I think we can create another branch for code cleanup and do the work there , instead of directly deleting from master branch .

**Comment by DishantK1807** [comment]
@kamishettysreeja25 : I will be deleting both of them now

created a new branch: code_cleanup

**Comment by DishantK1807** [comment]
Deleted branches: 
- Unit_tests
- theme
- stats
- remove-sessionhelper
- edit-news-comments
- Travis_config

As they were stale and of no use.

**Comment by DishantK1807** [comment]
Deleted branches:
- admin_settings
- user_model
- db_maintenance
- code_readability 
- export_database

**Comment by DishantK1807** [comment]
Fixing here. #135 
This issue can be closed(duplicate issue)
