### ISSUE TITLE
Set up Travis CI and Codecoverage.io

### ISSUE THREAD

**Issue by mariobehling** [fossasia/engelsystem#6]
We need to be sure all our code is running and tested. Please set up Travis and Codecoverage to ensure this.

**Comment by vuhung** [comment]
Ops, sorry, travis is cloud based :) 

I thought it was Jenkins.

@mariobehling Do we already have a server (VPS) for travis, codecoverage?

**Comment by vuhung** [comment]
@mariobehling: Do you mean https://codecov.io/ ?

**Comment by mariobehling** [comment]
@vuhung Yes, is it suitable?

Regarding VPS - We do not need it. We can integrate it with GitHub and use Heroku: http://travis-ci.org

**Comment by vuhung** [comment]
@mariobehling : Yes, more than enough. We can get more out of travis.
