### ISSUE TITLE
Feature Request: Admin: Changing the databases via admin settings

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#62]
For managing different events on the same system we can change the databases via admin settings

I am creating a dropdown in which we can select through the existing databases.

![capture2](https://cloud.githubusercontent.com/assets/7828295/15819370/6913cefa-2c00-11e6-8c1a-b30c7b4b6284.PNG)

**Comment by DishantK1807** [comment]
Can we use mysql_connect() in this system for switching databases?

**Comment by hongquan** [comment]
We should define `event` table and make appropriate relation ship between other models (`User`, `Shift`...) and this `Event` model. We also improve admin to let manage by events.

**Comment by DishantK1807** [comment]
@hongquan : will be following this approach now.

**Comment by DishantK1807** [comment]
Closing this issue as new approach will be followed
