### ISSUE TITLE
Feature Request: Admin: Creating a drop-down option 

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#63]
I'll be creating a drop-down menu in Settings page for admin for choosing databases

**Comment by DishantK1807** [comment]
#62

**Comment by vuhung** [comment]
jQuery style dropdown list? :)

**Comment by DishantK1807** [comment]
@vuhung : yes. Like we have for themes and languages in settings

**Comment by DishantK1807** [comment]
But I'll need to create a new page for admin settings as the same page is also used by the user settings.

**Comment by DishantK1807** [comment]
Closing this issue as new approach will be followed.
