### ISSUE TITLE
Feature Guest : Guest can change the theme before registration

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#74]
Guest should be given option to change the theme before registration.

**Comment by hpdang** [comment]
I think we don't really need this. Can you just set the white background as default like attached image? Thanks. 
![screenshot from 2016-06-07 14 29 38](https://cloud.githubusercontent.com/assets/1658742/15857587/6dfe048c-2cbc-11e6-8259-26507cae04cb.png)

**Comment by sreejakshetty** [comment]
Yes , I can change it .I will set the background as white.
Thanks.
