### ISSUE TITLE
Admin : Shifts : Date/Time Picker for edit shifts view

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#77]
![screenshot from 2016-06-08 08 00 36](https://cloud.githubusercontent.com/assets/14835922/15881064/aa9c132c-2d50-11e6-9a81-bff10caf4f92.png)

**Comment by vuhung** [comment]
My impression for this screen:
1. Ui is so simple
2. Should replace with jQuery?

No excuse for being brief on mobile.

**Comment by sreejakshetty** [comment]
This page is only for admin to edit the shifts .  For editing shifts , I feel simple UI is better.
