### ISSUE TITLE
Shifts : Different timestamps saved for shifts

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#78]
![screenshot from 2016-06-08 08 03 49](https://cloud.githubusercontent.com/assets/14835922/15881089/e2ec3144-2d50-11e6-89db-eb3b86552148.png)
![screenshot from 2016-06-08 08 02 01](https://cloud.githubusercontent.com/assets/14835922/15881090/e3480cb2-2d50-11e6-8611-f7b9fd24eada.png)

**Comment by hpdang** [comment]
Hi Sreeja, 

the What do you want to do? (Description of job types) at the bottom of the form (is it a default) or it will change based on inputs of user-admin?

**Comment by sreejakshetty** [comment]
Hi hpdang,
![screenshot from 2016-06-11 13 55 41](https://cloud.githubusercontent.com/assets/14835922/15984097/33cde7dc-2fdc-11e6-8879-f20a46327dcf.png)
Description of job types are available here.We can also add the information after a user/angel wants to be a angel . what do you say?
