### ISSUE TITLE
Feature Request: Managing different events on the same system

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#80]
This feature will enable the admin to manage different events on the same system.

**Comment by DishantK1807** [comment]
@hpdang : Can you please provide with the suggestions for the admin pages, for managing different events on the same system.

**Comment by hpdang** [comment]
I am thinking of something like Eventnook maybe. We don't have to make exactly the same though. What do you think? 
![screenshot from 2016-06-08 08 53 42](https://cloud.githubusercontent.com/assets/1658742/15885328/da0abd2e-2d56-11e6-9498-f6706658d2ac.png)
![screenshot from 2016-06-08 08 54 16](https://cloud.githubusercontent.com/assets/1658742/15885339/ec388b8e-2d56-11e6-8209-07f98df3b72f.png)

**Comment by DishantK1807** [comment]
@hongquan : What do you suggest ? My suggestion:
- We will make a new events page where the admin can make new events
- Users can register for specific events can change later if new events are added ( additional functionality- might not be required as of now though, as user can register for the shift which he/she wants to, belonging to any event)
- The description of the Event will be provided by the admin on the Events page, Just like as it is in the shift type page as shown below.
  ![capture12](https://cloud.githubusercontent.com/assets/7828295/15885680/678cdd34-2d76-11e6-9b25-251c18397d73.PNG)
- When any new event will be created, all the already registered users can register for the available shifts according to their angeltype.

@hpdang : Will the above mentioned features do?

**Comment by hpdang** [comment]
Hi Dishant, I am not quite sure if I understand you. For the Event Manage Page, I would like to have something like Eventnook where you can view  1. Upcoming event 2. Create a new event 3. Look at the past events. 
- Create a new event tab: it should generate a brand new system (Fresh). a) Admin will provide the new description. b) A default set of angeltypes can be used for different events and admin can make changes accordingly. c) The volunteers list should be empty at this point, existing angels do not need to sign up again but need to join the new event in order to sign up for shifts (similar to GitHub member to join different repositories) then his/her data can be showed on All Angels table of the new event. 
- Past event tab: admin will be able to view past event including shifts, angeltype, and a list of angels who signed up for that particular event.   

I suggest we discuss with @hongquan and @vuhung all the details before proceed further.

**Comment by hongquan** [comment]
I think @hpdang explained well.

> When any new event will be created, all the already registered users can register for the available shifts according to their angeltype.

No. When registering, user doesn't need to be assigned to any event. After she registers, she can go to Profile page or Event list page and choose which event to join. Or the website admin will assign her to appropriate event.

From the database view, there will be many-to-many relationship in these pairs of models:
- `User` - `Event`: 1 event can have many user. 1 user can belong to many events.
- `AngelType` - `Event`: 1 event can have many angeltype. 1 angeltype can be reused in many events.
- `User` - `AngelType`.

@DishantK1807 Do you know how to implement many-to-many relationships in database?

**Comment by DishantK1807** [comment]
@hongquan : got it now. Yes I know about many-to-many relationships in database, but haven't implemented them yet. 
Also working on creating new feature ( Events page) is a big task and will take time. I'll dividing it into smaller issues to achieve this goal. I need to get my feet wet with the current coding system (writing model, controller, view and pages files for the system) to design a new system.
Also while going throught the code for this issue I realized that I didn't make any changes in the model and controller files of the user when I updated the user table, ( for the registration form). Though this won't be causing any problem as of now, but they need to updated. Moreover I'll get more idea about the coding while working on them. Also the added fields need to be added in the settings foelds as well( like updating the current city field option), and certain other things before we can start working on the events page.

Also I'll getting more developers for this issue (already in talk with some). Will be changing it's milestone as there are many other things that needs to be implemented for achieving this goal. And we'll working step by step discussing it with @hpdang for suggestions on requirements.

**Comment by hongquan** [comment]
For implementing many-to-many relation, people will create an intermediary join table, which has foreign keys to the two related tables. You can read more here: https://laravel.com/docs/5.1/eloquent-relationships#many-to-many

**Comment by DishantK1807** [comment]
@hongquan: Thank you. I'll refer to them while designing the database.

**Comment by DishantK1807** [comment]
Fixed here: #222
