### ISSUE TITLE
Signal/dispatcher implementation

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#9]
Engelsystem does not use any framework. For the implementation of signal/dispatcher concept do we need to port the system to a framework? or we can just reuse the libraries suggested without porting it to any framework?

**Comment by vuhung** [comment]
@hongquan : What do you think?

For the time frame of this GSoC project, I think reusing the suggested libs would be a good idea. 
Using new frameworks will add more complexity to the project.

**Comment by mariobehling** [comment]
@DishantK1807 Please reuse the existing libraries.

**Comment by hongquan** [comment]
From my old message in Slack:

> Engelsystem does not use any framework, this pattern may not exists. So I think you have to either:
> - Implement a full signal/dispatcher system. It may be overwhelmed, but it can be used for more than this notification issue. You can find some libraries here: https://github.com/ziadoz/awesome-php
> - Implement a function and put its call to anywhere you feel needed. This is more about copy/paste than the signal/dispatcher solution.

I think @DishantK1807 can go with 2nd solution: No signal/dispatcher at all. Just make a function, add its call to anywhere there is action of changing shift (normally in admin). Implementing a full signal/dispatcher system will involve integrating it with engelsystem codebase is still difficult.

**Comment by DishantK1807** [comment]
Closing this issue, as it was a general query.
