### ISSUE TITLE
Updating users_view.php

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#90]
Updating the code for users_view.php for the changes made in the user table.

**Comment by mariobehling** [comment]
> changes made in the user table.

Why is this issue necessary? Please cross-reference issues.

**Comment by sreejakshetty** [comment]
![screenshot from 2016-08-01 08 43 41](https://cloud.githubusercontent.com/assets/14835922/17282512/2103e916-57c4-11e6-8410-9467f3ada7c4.png)
@DishantK1807  We have updated user_view.php with the changes made in the user table. We can close this issue now.
