### ISSUE TITLE
Adding more search options in user_model

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#94]
Implementing function for search by:
- Facebook link (get user details by facebook link)
- Github link (get user details by Github link)
- Twitter link (get user details by twitter link)
- Organization (get user details by organization name)

**Comment by DishantK1807** [comment]
Reviewed the code for for user_view and user_controllers, for implementing search. The current method that is used implement for search does not require any additional functions for search to return values of facebook, github, twitter of the user. 

We just need to update the users_view so that this information can be displayed and search. #90 
These functions are not required as of now.

![capture1](https://cloud.githubusercontent.com/assets/7828295/17277360/bf6f2090-575e-11e6-8595-7a96a9a6ba00.PNG)

Closing this issue.

**Comment by sreejakshetty** [comment]
@DishantK1807 
https://github.com/fossasia/engelsystem/issues/3. I have implemented search in All users page. search goes through all the fields of user table. so we need not extend it to other fields.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: That's what I commented above and closed this issue after reviewing the code. Thank you.
